Improve the rendering of harbors
baremaps/openstreetmap-vecto pull request #48
Opened 2021-12-16 15:25 UTC by Yahia1018

2021-12-16 17:11 UTC, bchapuis requested changes
Thanks, overall the changes look good. I added some comments and questions that we deed to adress before merging.

2021-12-16 17:11 UTC, bchapuis commented on style.json
> +    "layout" : {
You can probably remove the layout.

2021-12-16 17:11 UTC, bchapuis commented on style.json
> +      "line-color" : "rgba(242, 239, 233, 1)",
you can use rgb instead of rgba:
rgb(242, 239, 233)

2021-12-16 17:11 UTC, bchapuis commented on style.json
> +    "layout" : {
I think you can remove the layout. It is not used in the highway_path layer.

2021-12-16 17:11 UTC, bchapuis commented on style.json
> +    "id" : "highway_path_port_ouchy",
The id should be generic. For instance: highway_path_private.

2021-12-16 17:11 UTC, bchapuis commented on style.json
> +        "stops" : [ [ 12, 0.5 ], [ 18, 2 ] ]
Stops should be used carefully and consistently in the stylesheet. Have you thought about some rules and convention we may apply everywhere?

2021-12-16 17:11 UTC, bchapuis commented on style.json
> +        "stops" : [ [ 15, 8 ], [ 16, 11 ], [ 20, 11 ] ]
Same here, are there some rules for defining the stops when they are applied to the labels?

2021-12-16 17:11 UTC, bchapuis commented on style.json
> +      "text-halo-color" : "rgba(255,255,255,0.8)",
Is there a reason why we have an 80% opacity here?

2021-12-17 08:54 UTC, Yahia1018 commented on style.json
> +    "id" : "highway_path_port_ouchy",
Ha yes, sorry I forgot to change it after our discussion and my changes.

2021-12-17 09:34 UTC, Yahia1018 commented on style.json
> +    "layout" : {
I copied from the highway_path (actual line 782) and there is the same layout, do yo want to remove it from both ?

2021-12-17 09:36 UTC, Yahia1018 commented on style.json
> +    "layout" : {
Effectively, I removed it.

2021-12-17 09:38 UTC, Yahia1018 commented on style.json
> +      "line-color" : "rgba(242, 239, 233, 1)",
Oh okay, I change it and I'll use it in the future.

2021-12-17 09:48 UTC, bchapuis commented on style.json
> +    "layout" : {
yes, you can remove the both.

2021-12-17 10:24 UTC, Yahia1018 commented on style.json
> +        "stops" : [ [ 12, 0.5 ], [ 18, 2 ] ]
Ok, I see. I found it difficult to etablish perfect conventions, the only things I actually see is to fix maximums (width for example) per zoom level, and a maximum of stops (maybe depending on the min zoom), I saw that the max stops you used is 6.

I will think about it more deeply.

2021-12-17 11:00 UTC, Yahia1018 commented on style.json
> +        "stops" : [ [ 15, 8 ], [ 16, 11 ], [ 20, 11 ] ]
Honestly, it was a little by visual feeling and by a comparison with OpenStreetMap, for example here the letters must not take too much place when dezooming. But I have a personal convention that it must have a stop at the min level if there is one.

I also wanted to avoid this sort of problem (a letter above another letter) :

<img width="126" alt="Capture d’écran 2021-12-17 à 11 55 32" src="https://user-images.githubusercontent.com/91720525/146534539-c5785113-fc4f-4347-93f8-c7bb92911dcb.png">

2021-12-17 11:02 UTC, Yahia1018 commented on style.json
> +      "text-halo-color" : "rgba(255,255,255,0.8)",
No, sorry, it is when I use Maputnik color picker. I change that.

2021-12-17 12:26 UTC, bchapuis commented on style.json
> +        "stops" : [ [ 12, 0.5 ], [ 18, 2 ] ]
Ok, we can merge the PR and document this elsewhere.

2021-12-17 12:27 UTC, bchapuis commented on style.json
> +      "text-halo-color" : "rgba(255,255,255,0.8)",
I read a bit too fast and see now that it is a halo. In that case, the opacity makes sence, you can leave it that way.

2021-12-17 12:28 UTC, bchapuis commented
It makes sense to push your change as soon as possible as they probably address the comments.

2021-12-17 13:44 UTC, Yahia1018 commented on style.json
> +      "text-halo-color" : "rgba(255,255,255,0.8)",
Ok, perfect !

2021-12-30 20:50 UTC, bchapuis approved these changes

2021-12-30 20:50 UTC, merged